---
kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: git

steps:
  - name: build
    image: docker
    privileged: true
    environment:
      TOKEN:
        from_secret: registry_token
      VITE_FOOTER_NOTE_1: "LNVPS is a trading name of Apex Strata Ltd, a company registered in Ireland."
      VITE_FOOTER_NOTE_2: "Comany Number: 702423, Address: Suite 10628, 26/27 Upper Pembroke Street, Dublin 2, D02 X361, Ireland"
    commands:
      - dockerd &
      - docker login -u registry -p $TOKEN registry.v0l.io
      - docker build -t registry.v0l.io/lnvps-web:latest .
      - docker push registry.v0l.io/lnvps-web:latest
      - kill $(cat /var/run/docker.pid)
